{
    "order": {
        "user_id": 123,
        "total": 99.99
    },
    "orderDetail": [
        {
            "product_id": 456,
            "quantity": 2,
            "sale_price": 49.99
        },
        {
            "product_id": 789,
            "quantity": 1,
            "sale_price": 0.01
        }
    ]
}