POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username" : "BeyonderAdmin",
  "email" : "fajri.illahi@zenrooms.com",
  "password" : "Fajri@123",
  "name" : "Fajri Illahi",
  "role" : "admin"
}

###

POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username" : "user",
  "password" : "Fajri@123"
}

###

GET localhost:8080/api/v1/auth/all-users
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTY3ODc4MzQzNSwiaWF0IjoxNjc4Nzc5ODM1LCJzY29wZSI6IiJ9.jmmcbeO5lNreVODTm1Mn_TP8jSKm6O5noOS1iQDYVEvbp6N7oNDXJJAzeKA_PlQsTyd5k4TOLJJi-2yejiysTMs2bPYPrWZ59njv7vRkXT26r1xyVp7flQJnY1z-qOrmA2sP8C0Dww6I0Eq6Ir7V3qSH9ie_tn3C0BxaxtVCmMxHii4HH9Xn7X-64Gaee1yGZ9ef0_BFMHeBKaSCWOMTw4HhTW8RceaM-zoV-z5Vbulq2Fhu1k483ZDQc2cWCJIWZ4KzYT0yX7vN8qzw-1Ki3ZqFam3J0O0vE81uGd3z4L8l7Jmc16dWErxSYeCx2f1lgIWLBex-CFFh8DRdPffJAQ

###


GET localhost:8080/api/v1/auth/all-users
Authorization: Bearer
eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiSXFiYWwyIiwiZXhwIjoxNjc4ODYxMjgyLCJpYXQiOjE2Nzg4NTc2ODJ9.qK2W9wiVtS5LnvjkHzqOfUcFWMvmXRdOdcC6bz-yPPViW3SA4pG3RAgFNe9Pi3EIlBafcZp0DEoPNMK3NG_OKEmREEWuDeXN6cXXPtW1A1ZJ1lVwjn07Cp3KTvr8slO09KLRdcFH3-FNZ6jS5UkxDfjkKTNVRYBxmVkeAErtwoGBs2jti8g09cDPQjjaReG30MCds_X-VeN3UR0qzEgO_hm7a_yO9GupjZtRKKI8DUfK5rJ-w006k6oZFAEGbaEABLRVMzd_aCdRu7KQf9msPM49016vEGwMMhUgFqRTIIS8RypKdqp8VvH8ya4d7uI9T7df5NCPni3pWsB8Rz92mg