on: [push]
name: CI/CD

jobs:
  build-job:
      runs-on: ubuntu-latest
      container: maven:latest
      env:
        LATEST_VERSION: '1.8'
      steps:
      - uses: actions/checkout@v2
      - name: Build job
        run: |
          cd auth-service
          mvn compile -Dmaven.compiler.target='11'
          cd ../
          cd category-service
          mvn compile -Dmaven.compiler.target='17'
          cd ../
          cd gateway-service
          mvn compile -Dmaven.compiler.target='11'
           cd ../
          cd order-service
          mvn compile -Dmaven.compiler.target='17'
          cd ../
          cd product-service
          mvn compile -Dmaven.compiler.target='17'
          cd ../
          cd user-service
          mvn compile -Dmaven.compiler.target='17'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
          
  unit-test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit Test job
      run: |
        cd auth-service
        mvn test -Dmaven.compiler.target='11'
         cd ../
        cd category-service
        mvn test -Dmaven.compiler.target='17'
         cd ../
        cd gateway-service
        mvn test -Dmaven.compiler.target='11'
         cd ../
        cd order-service
        mvn test -Dmaven.compiler.target='17'
         cd ../
        cd product-service
        mvn test -Dmaven.compiler.target='17'
         cd ../
        cd user-service
        mvn test -Dmaven.compiler.target='17'
